### ISSUE TITLE
Avoid using magic numbers

### ISSUE THREAD

**Issue by hlinero** [linero-tech/module-306-a-team#61]
https://github.com/linero-tech/module-306-a-team/blob/8b4c97d8b1e99a0517aa1ba1e7b663a06362fa03/app/src/main/java/se/linerotech/quizkampen/ResultActivity.kt#L72

The `"10"` is called a "Magic Number" because I have no idea why you have selected `10` and not `20` or `30` or some other number. To avoid this, you shall create a variable called `numberOfQuestions` or `questionsToRetrieve`, set the value of `10` to that variable and then pass that variable. In that way it is clear what the number means.

---------------

https://github.com/linero-tech/module-306-a-team/blob/8b4c97d8b1e99a0517aa1ba1e7b663a06362fa03/app/src/main/java/se/linerotech/quizkampen/GameActivity.kt#L234

Here you also use a magic number. Why `5`?

**Comment by erikscc** [comment]
I fixed the first part , in the second part there are 5 because it is checking the logic for 4 or 2 buttons to appear on the screen. I have been storing 4 answers and 1 correct answer in the variable if false , the true question then 2, and the correct answer as third. That's why I check 5 or 3 , depending on that It will show accessible buttons. I am working on doing it better in another way , but it is time-consuming, this is a dummy version.
